name: Build and Release

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64, 386]
        include:
          - arch: amd64
            name: x64
          - arch: 386
            name: x86
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install dependencies
        run: go mod download
          
      - name: Build
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: windows
        run: |
          # Build with rsrc.syso to include the icon
          cp .build/rsrc.syso .
          go build -ldflags="-H windowsgui" -v -o Zengo-${{ matrix.name }}.exe
          rm rsrc.syso
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zengo-Windows-${{ matrix.name }}
          path: Zengo-${{ matrix.name }}.exe

  create-release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Display structure of downloaded files
        run: ls -R

      - name: Package executables into zip files
        run: |
          zip -j Zengo-x64.zip Zengo-Windows-x64/Zengo-x64.exe
          zip -j Zengo-x86.zip Zengo-Windows-x86/Zengo-x86.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Zengo ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            Zengo-x64.zip
            Zengo-x86.zip
